name: Tag Docker image

env:
  IMAGE_NAME: "madailei/mr-ebbelink-fe"

on:
  workflow_dispatch:
    inputs:
      sourceTag:
        description: The tag of the image (e.g. madailei/mr-ebbelink-fe:[SOURCE_TAG])
        required: true
      destinationTag:
        description: Destination tag
      tagAsLatest:
        description: Add the `latest` tag to this image
        type: boolean

jobs:

  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Tag docker image
      run: |
        docker tag ${{ env.IMAGE_NAME }}:${{ github.event.inputs.sourceTag }} ${{ env.IMAGE_NAME }}:${{ github.event.inputs.destinationTag }}
        
        if (${{ github.event.inputs.tagAsLatest }}); 
        then
          docker tag ${{ env.IMAGE_NAME }}:${{ github.event.inputs.sourceTag }} ${{ env.IMAGE_NAME }}:latest
        fi
        
        docker push ${{ env.IMAGE_NAME }} --all-tags
