name: Docker Image CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      run: |
        dockerImageTag="madailei/mr-ebbelink-fe:$(date +%s)"
        echo $dockerImageTag
        docker build . --file Dockerfile --tag $dockerImageTag
        docker image push $dockerImageTag
