name: Docker Image CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "madailei/mr-ebbelink-fe:$(date +%s)" >> $dockerImageTag
        docker build . --file Dockerfile --tag $dockerImageTag
  
  push:
    runs-on: ubuntu-latest
    
    steps:
      - name: docker push
        run: docker image push $dockerImageTag
