name: Tag Docker image

env:
  IMAGE_NAME: "madailei/mr-ebbelink-fe"

on:
  workflow_dispatch:
    inputs:
      sourceTag:
        description: The tag of the image to retag (e.g. `continuous-2021-11-27-epoch-1638028004` from ${{ env.IMAGE_NAME }}:continuous-2021-11-27-epoch-1638028004)
        required: true
      destinationTag:
        description: The tag of the image to add to the sourceImage
      tagAsLatest:
        description: Add the `latest` tag to this image

jobs:

  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Tag docker image
      run: |
        echo "docker tag ${{ env.IMAGE_NAME }}:${{ github.event.inputs.sourceTag }} ${{ env.IMAGE_NAME }}:${{ github.event.inputs.destinationTag }}"
        if (${{ github.event.inputs.tagAsLatest }}); 
        then
          echo "docker tag ${{ env.IMAGE_NAME }}:${{ github.event.inputs.sourceTag }} ${{ env.IMAGE_NAME }}:latest"
        fi

